export const Tags = Object.freeze({
  P4: "Perforce",
  CUDA: "CUDA",
  PTX: "PTX",
  GPU: "GPU",
  PYTORCH: "PyTorch",
  ML: "Machine Learning",
  REACT: "React",
  JS: "Javascript",
  TS: "Typescript",
  SQL: "SQL",
  HTML: "HTML",
  CSS: "CSS",
  ASYNC: "Async",
  GIT: "Git",
  SASS: "SASS",
  FIREBASE: "Firebase",
  PYTHON: "Python",
  SWIFT: "Swift",
  OCAML: "OCaml",
  FLASK: "Flask",
  KOTLIN: "Kotlin",
  JC: "Jetpack Compose",
  CPP: "C++",
  CMD: "Command Line",
  AUTH: "Auth",
  VERCEL: "Vercel",
  LLVM: "LLVM",
  DOCKER: "Docker",
  JENKINS: "Jenkins",
  MT: "Multithreading",
  CONCURRENCY: "Concurrency",
  ASM: "Assembly",
  C: "C",
  TRANSFORMERS: "Transformers",
  LLAMA: "LlamaLLM",
  PANDAS: "Pandas",
  MATPLOTLIB: "Matplotlib",
  Encoding: "Video Encoding",
  OpenCL: "OpenCL",
  OpenGL: "OpenGL",
  VULKAN: "Vulkan",
  DIRECTX: "DirectX",
  PGO: "PGO",
  PERF: "perf",
  LANGCHAIN: "LangChain",
  AZURE: "Azure",
  ERPC: "eRPC",
  GEE: "Google Earth Engine",
  WEBGL: "WebGL",
  GLSL: "GLSL",
  SCALA: "Scala 3",
  STATIC_ANALYSIS: "Static Analysis",
  COMPILERS: "Compilers",
});
